# The name of the workflow
name: build

# What conditions trigger the workflow
#  In this case, all pushes and pull requests
on:
  pull_request:
  push:
    branches:
      - master

# The jobs that will be run, usually in parallel
jobs:
  coverage:
    name: Test and publish test coverage

    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@master

      - uses: actions/setup-node@master
        with:
          node-version: "12"

      - run: npm install

      - uses: paambaati/codeclimate-action@v2.4.0
        env:
          CC_TEST_REPORTER_ID: ${{ secrets.CodeClimateReporterId }}
        with:
          coverageCommand: npm run coverage
          coverageLocations: "./coverage/clover.xml:clover"
          debug: true
